/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Analysis: typeof import('./src/components/Analysis.vue')['default']
    Cluster: typeof import('./src/components/cluster.vue')['default']
    ElBtn: typeof import('element-plus/es')['ElBtn']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElColumn: typeof import('element-plus/es')['ElColumn']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTablePane: typeof import('element-plus/es')['ElTablePane']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ErrorAnalysis: typeof import('./src/components/ErrorAnalysis.vue')['default']
    LineChart: typeof import('./src/components/LineChart.vue')['default']
    LineChart1: typeof import('./src/components/LineChart1.vue')['default']
    Loss: typeof import('./src/components/Loss.vue')['default']
    Pie: typeof import('./src/components/Pie.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slotname_distribute: typeof import('./src/components/Slotname_distribute.vue')['default']
    Table: typeof import('./src/components/table.vue')['default']
  }
}
